### PR TITLE
Prevent Deployment on Fork Repositories for Dev, Staging, and Production

### PR DESCRIPTION
**Pull request by destinedcodes**
### Description
This pull request updates the CI/CD configuration to prevent deployments to development, staging, and production environments from forked repositories.

### Objective
Enhance the deployment process by ensuring that deployments from forked repositories are restricted, thereby avoiding potential issues and ensuring that only trusted sources can deploy to critical environments.

### Changes Made
- **Updated the CI/CD Workflow:** Modified the github worflows to include a condition that prevents deployments from forked repositories.
- **Scope:** The change applies to all environments: development, staging, and production.
- **Configuration Improvement:** Added a check to ensure that the deployment job only runs if the repository is not a fork.

### Checklist
- 🚨 Please review the contribution guideline for this repository.
- Code adheres to the project's style guidelines.
- This PR does not include plagiarized content.
- The title and description of the PR clearly outline the changes made.
- The PR targets the dev branch.
- Commit messages follow the specified format.
- Code changes pass all linting checks and unit tests.
- Modifications are limited to the necessary files.

### CODE REVIEW

**Review by Godhanded — APPROVED** [review]

**Review by chimaihueze — APPROVED** [review]

**Comment by destinedcodes** [comment]
Don't merge yet 🙏🏽. An intern would do same for production and staging

**Comment by chimaihueze** [comment]
> Don't merge yet 🙏🏽. An intern would do same for production and staging

okay. won't be merging this

**Comment by destinedcodes** [comment]
> > Don't merge yet 🙏🏽. An intern would do same for production and staging
> 
> okay. won't be merging this

All good @chimaihueze. this PR aims to avoid unnecessary attempt to deploy on forks.

**Comment by chimaihueze** [comment]
> > > Don't merge yet 🙏🏽. An intern would do same for production and staging
> > 
> > 
> > okay. won't be merging this
> 
> All good @chimaihueze. this PR aims to avoid unnecessary attempt to deploy on forks.

alright thanks. will be merging now

**Review by chimaihueze — APPROVED** [review]

**Pull request merged**
